config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/earlyaccess")
  #root to: "recipes#index"

  devise_for :users,
             :path => "",
             :path_names => {
              :sign_in => 'login',
              :sign_out => 'logout',
              :sign_up => 'signup' },
             controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  resources :recipes, except: [:update, :destroy, :edit]
  namespace :recipes do
    resources :v, controller: "/recipe_versions", except: [:new, :create] do
      resources :versions, controller: "/recipe_versions", only: [:new, :create]
    end
  end

  get "*path", to: redirect("/404")
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include Hashid::Rails

  has_many :recipe_versions, dependent: :destroy
  belongs_to :user

  validates :recipe_versions, length: { minimum: 1 }
  validates_presence_of :title
  validates_associated :recipe_versions

  accepts_nested_attributes_for :recipe_versions
end

app/controllers/recipes_controller.rb
class RecipesController < AuthenticatedController

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = current_user.recipes.find_by_hashid(params[:id])
  end

  def new
    @recipe = Recipes::NewForm.new.recipe
    gon.recipe = Recipes::NewForm.new.gon
  end

  def edit
  end

  def create
    form = Recipes::CreateForm.new(params: params, user: current_user)
    if form.save
      redirect_to action: :show, id: form.recipe.hashid
    else
      @recipe = form.recipe
      gon.recipe = form.gon
      render :new
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipes/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "pages/recipes/index", media: 'all',
                          'data-turbolinks-track': 'reload' %>
<% end %>

<div class="col-10 mx-auto mt-4">
  <h2 class="font-weight-bolder text-white">My Recipes</h2>
  <div>
    <div class="row">
      <% if @recipes.blank? %>
        <div class="col-xl-3 col-md-4 col-sm-6 mb-2">
          <div class="card border-4 border-info">
            <%= link_to new_recipe_path do %>
              <div class="card-body text-center">
                <i class="far fa-plus-square fa-3x mb-2 text-info"></i>
                <p class="card-title font-weight-bold text-white">Create Your First Recipe</p>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <% @recipes.each do |recipe| %>
          <div class="col-xl-3 col-md-4 col-sm-6 mb-2">
            <div class="card border-4 border-info h-100">
              <%= link_to recipe_path recipe do %>
                <div class="card-body">
                  <h5 class="card-title font-weight-bolder text-white" title="<%= recipe.title %>"> <%= recipe.title %> </h5>
                  <div class="border-top w-25 pb-2">
                  </div>
                  <div class="card-text text-white font-weight-light font-space-md"><%= recipe.recipe_versions.count %> 
                    <% if recipe.recipe_versions.count == 1 %>
                      version
                    <% else %>
                      versions
                    <% end %>
                  </div>
                  <div class="card-text text-muted font-weight-light font-space-md">Created on <%= recipe.created_at.strftime("%b %-d, %Y") %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="col-lg-6 col-md-8 col-sm-10 col-10 mx-auto mt-4">

  <div class="mb-2">
    <h2 class="font-weight-bolder mb-3">New Recipe</h2>
  </div>

  <% if @recipe.errors.present? %>
    <div class="alert alert-danger text-white">
      <% @recipe.errors.full_messages.each do |error| %>
        <p class="mb-0"><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt-2 vueable">
    <%= form_for(@recipe, url: {action: "create"}, html: {class: "form"}) do |recipe_f| %>

      <%= recipe_f.label :title, "Name", class: "text-muted" %>
      <%= recipe_f.text_field :title, class: "recipe-input mb-3" %>

      <%= recipe_f.fields_for :recipe_versions do |recipe_version_f| %>

        <%= recipe_version_f.label :description, "Description",
                                   class: "text-muted" %>
        <%= recipe_version_f.text_field :description, class: "recipe-input" %>

        <ingredients-edit class="my-4"
        :original-recipe-ingredients="recipe.recipe_versions[0].recipe_ingredients"
        name-prefix="recipe[recipe_versions_attributes][0][recipe_ingredients_attributes]">
        </ingredients-edit>

        <steps-edit class="mt-4"
        :original-recipe-steps="recipe.recipe_versions[0].recipe_steps"
        name-prefix="recipe[recipe_versions_attributes][0][recipe_steps_attributes]">
        </steps-edit>
      <% end %>
      <div class="col-12 d-flex flex-column flex-sm-row justify-content-center justify-content-sm-end mb-2 mt-4 mt-sm-0">
        <%= link_to "Cancel", recipes_path, class: "btn btn-outline-danger btn-border-radius order-1 text-white d-block px-3 py-2 d-sm-flex justify-content-center align-items-center" %>
        <%= recipe_f.submit "Save", class: "btn btn-outline-primary btn-border-radius text-white order-0 order-sm-2 d-block px-3 py-2 mb-2 mb-sm-0 ml-sm-3 justify-content-center align-items-center" %>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "components/ingredients/edit" %>
<%= render partial: "components/steps/edit" %>

<script>
  $(document).ready(function() {
    new Vue({
      el: $('.vueable')[0],
      data: { 
        recipe: gon.recipe
      }
    });
  });
</script>

<script type="text/javascript">
  var autoExpand = function (field) {

  // Reset field height
  field.style.height = 'inherit';

  // Get the computed styles for the element
  var computed = window.getComputedStyle(field);

  // Calculate the height
  var height = parseInt(computed.getPropertyValue('border-top-width'), 10)
               + parseInt(computed.getPropertyValue('padding-top'), 10)
               + field.scrollHeight
               + parseInt(computed.getPropertyValue('padding-bottom'), 10)
               + parseInt(computed.getPropertyValue('border-bottom-width'), 10);
  field.style.height = height + 'px';
};
</script>

<script type="text/javascript">
  document.addEventListener('input', function (event) {
    if (event.target.tagName.toLowerCase() !== 'textarea') return;
    autoExpand(event.target);
  }, false);
</script>

app/views/recipes/show.html.erb
<div class="col-xl-8 col-10 mx-auto mt-4">
  <h2 class="font-weight-bolder text-white"><%= @recipe.title %></h2>
  <div>
    <div class="row">
      <% @recipe.recipe_versions.each_with_index do |recipe_version, index| %>
        <div class="col-12">
          <% if index > 0 %>
            <div class="text-center">
              <%= icon('fas', 'long-arrow-alt-down', class: 'fa-2x text-white') %>
            </div>
          <% end %>
          <div class="card border-4 border-info">
            <%= link_to recipes_v_path recipe_version do %>
              <div class="card-body">
                <h5 class="card-title font-weight-bolder text-white" title="<%= recipe_version.description %>">
                  <% if recipe_version.description.present? %>
                    <%= recipe_version.description %>
                  <% else %>
                    No description
                  <% end %>
                </h5>
                <div class="border-top w-25 pb-2">
                </div>
                <div class="card-text text-white font-weight-light font-space-md mb-1">
                  <% if recipe_version.locked_at.present? %>
                    <%= icon('fas', 'lock', class: 'mr-1 text-danger') %>
                    Recipe version locked
                  <% else %>
                    <%= icon('fas', 'unlock', class: 'mr-1 text-primary') %>
                    Recipe version unlocked
                  <% end %>
                </div>
                <div class="card-text text-muted font-weight-light font-space-md">
                  Created on <%= recipe_version.created_at.strftime("%b %-d, %Y") %>
                  <% if recipe_version.locked_at.present? %>
                  | Locked on <%= recipe_version.locked_at.strftime("%b %-d, %Y") %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>