config/routes.rb
Rails.application.routes.draw do

  root to: redirect("/earlyaccess")
  #root to: "recipes#index"

  devise_for :users,
             :path => "",
             :path_names => {
              :sign_in => 'login',
              :sign_out => 'logout',
              :sign_up => 'signup' },
             controllers: { registrations: "users/registrations", sessions: "users/sessions" }

  resources :recipes, except: [:update, :destroy, :edit]
  namespace :recipes do
    resources :v, controller: "/recipe_versions", except: [:new, :create] do
      resources :versions, controller: "/recipe_versions", only: [:new, :create]
    end
  end

  get "*path", to: redirect("/404")
end

app/models/recipe_version.rb
class RecipeVersion < ApplicationRecord
  include Hashid::Rails

  scope :unlocked, -> { where(locked_at: nil) }
  scope :locked, -> { where.not(locked_at: nil) }

  belongs_to :user
  belongs_to :recipe
  belongs_to :parent_recipe_version, class_name: "RecipeVersion", optional: true
  has_many :recipe_ingredients, -> { order(position: :asc) }, inverse_of: :recipe_version, dependent: :destroy
  has_many :recipe_steps, -> { order(position: :asc) }, inverse_of: :recipe_version, dependent: :destroy
  has_one :child_recipe_version, class_name: "RecipeVersion", foreign_key: :parent_recipe_version_id

  validates_presence_of :parent_recipe_version_id
  validates_associated :recipe_ingredients, :recipe_steps
  validates :recipe_steps, length: { minimum: 1 }
  validates :recipe_ingredients, length: { minimum: 1 }
  validate :not_unlocking_version
  
  before_validation :reorder_steps
  before_validation :reorder_ingredients

  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
  accepts_nested_attributes_for :recipe_steps, allow_destroy: true

  def locked=(value)
    if value
      self.locked_at = Time.now
    else
      self.locked_at = nil
    end
  end

  private

  def reorder_steps
    self.recipe_steps.each.with_index do |recipe_step, index|
      recipe_step.position = index
    end
  end

  def reorder_ingredients
    self.recipe_ingredients.each.with_index do |recipe_ingredient, index|
      recipe_ingredient.position = index
    end
  end

  def not_unlocking_version
    if self.locked_at_was.present? && self.locked_at.blank?
      errors.add(:base, "Cannot unlock a version once it's locked.")
    end
  end
end

app/controllers/recipe_versions_controller.rb
class RecipeVersionsController < AuthenticatedController
  def index
  end

  def show
    @recipe_version = RecipeVersion.where(user: current_user).find_by_hashid!(params[:id])
  end

  def new
    @recipe_version = RecipeVersion.locked.where(user: current_user).find_by_hashid!(params[:v_id])
    @recipe_version.assign_attributes(parent_recipe_version_id: @recipe_version.id)
    gon.recipe_version = RecipeVersions::NewForm.new(@recipe_version).gon
  end

  def edit
    @recipe_version = RecipeVersion.unlocked.where(user: current_user).find_by_hashid!(params[:id])
    gon.recipe_version = RecipeVersions::NewForm.new(@recipe_version).gon
  end

  def create
    form = RecipeVersions::CreateForm.new(
      parent_recipe_version: parent_recipe_version, params: params, user: current_user
    )
    if form.save
      redirect_to action: :show, id: form.recipe_version.hashid
    else
      @recipe_version = form.recipe_version
      gon.recipe_version = form.gon
      render :new
    end
  end

  def update
    form = RecipeVersions::UpdateForm.new(
      recipe_version_hashid: params[:id], params: params, user: current_user
    )
    if form.save
      redirect_to action: :show, id: form.recipe_version.hashid
    else
      @recipe_version = form.recipe_version
      gon.recipe_version = form.gon
      render :edit
    end
  end

  def destroy
  end

  private

  def parent_recipe_version
    @parent_recipe_version ||=  RecipeVersion.locked
                                             .where(user: current_user)
                                             .find_by_hashid!(params[:v_id])
  end

  def recipe_version
    @recipe_version ||= RecipeVersion.unlocked
                                     .where(user: current_user)
                                     .find_by_hashid!(params[:v_id])
  end
end

app/views/recipe_versions/edit.html.erb
<% content_for :components, true %>

<div class="col-lg-6 col-md-8 col-sm-10 col-10 mx-auto mt-4">
  <div class="mb-2">
    <h2 class="mb-4"><span class="text-muted">Editing</span> <span class="font-weight-bolder"><%= @recipe_version.recipe.title %> </span></h2>
  </div>

  <% if @recipe_version.errors.present? %>
    <div class="alert alert-danger text-white">
      <% @recipe_version.errors.full_messages.each do |error| %>
        <p class="mb-0"><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt-2 vueable">
    <%= form_for(
          @recipe_version,
          url: recipes_v_path(v_id: @recipe_version.hashid),
          method: :put,
          html: { class: "form" }
        ) do |f| %>

      <%= f.label :description, class: "text-muted" %>
      <%= f.text_field :description, class: "recipe-input" %>

      <ingredients-edit class="mt-4"
                        :original-recipe-ingredients="recipeVersion.recipe_ingredients"
                        name-prefix="recipe_version[recipe_ingredients_attributes]">
      </ingredients-edit>

      <steps-edit class="mt-4"
                  :original-recipe-steps="recipeVersion.recipe_steps"
                  name-prefix="recipe_version[recipe_steps_attributes]">
      </steps-edit>

      <div class="col-12 d-flex flex-column flex-sm-row justify-content-center justify-content-sm-end mb-2 mt-4 mt-sm-0">
        <%= link_to "Cancel", recipes_v_path(@recipe_version.hashid), class: "btn btn-outline-danger btn-border-radius order-1 text-white d-block px-3 py-2 d-sm-flex justify-content-center align-items-center" %>
        <%= submit_tag "Save", class: "btn btn-outline-primary btn-border-radius text-white order-0 order-sm-2 d-block px-3 py-2 mb-2 mb-sm-0 ml-sm-3 justify-content-center align-items-center" %>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "components/ingredients/edit" %>
<%= render partial: "components/steps/edit" %>

<script>
  $(document).ready(function() {
    new Vue({
      el: $('.vueable')[0],
      data: { 
        recipeVersion: gon.recipe_version
      }
    });
  });
</script>

<script type="text/javascript">
  var autoExpand = function (field) {

  // Reset field height
  field.style.height = 'inherit';

  // Get the computed styles for the element
  var computed = window.getComputedStyle(field);

  // Calculate the height
  var height = parseInt(computed.getPropertyValue('border-top-width'), 10)
               + parseInt(computed.getPropertyValue('padding-top'), 10)
               + field.scrollHeight
               + parseInt(computed.getPropertyValue('padding-bottom'), 10)
               + parseInt(computed.getPropertyValue('border-bottom-width'), 10);
  field.style.height = height + 'px';
};
</script>

<script type="text/javascript">
  document.addEventListener('input', function (event) {
    if (event.target.tagName.toLowerCase() !== 'textarea') return;
    autoExpand(event.target);
  }, false);
</script>

app/views/recipe_versions/new.html.erb
<% content_for :components, true %>

<div class="col-lg-6 col-md-8 col-sm-10 col-10 mx-auto mt-4">
  <div class="mb-2">
    <h2 class="mb-4"><span class="text-muted">New version of </span><span class="font-weight-bolder"><%= @recipe_version.recipe.title %></span> </h2>
  </div>

  <% if @recipe_version.errors.present? %>
    <div class="alert alert-danger text-white">
      <% @recipe_version.errors.full_messages.each do |error| %>
        <p class="mb-0"><%= error %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt-2 vueable">
    <%= form_for(
          @recipe_version,
          url: recipes_v_versions_path(v_id: @recipe_version.parent_recipe_version.hashid),
          method: :post,
          html: { class: "form" }
        ) do |f| %>

      <%= f.label :description, class: "text-muted" %>
      <%= f.text_field :description, class: "recipe-input" %>

      <ingredients-edit class="mt-4"
                        :original-recipe-ingredients="recipeVersion.recipe_ingredients"
                        name-prefix="recipe_version[recipe_ingredients_attributes]">
      </ingredients-edit>

      <steps-edit class="mt-4"
                  :original-recipe-steps="recipeVersion.recipe_steps"
                  name-prefix="recipe_version[recipe_steps_attributes]">
      </steps-edit>

      <div class="col-12 d-flex flex-column flex-sm-row justify-content-center justify-content-sm-end mb-2 mt-4 mt-sm-0">
        <%= link_to "Cancel", recipes_v_path(@recipe_version.parent_recipe_version.hashid), class: "btn btn-outline-danger btn-border-radius order-1 text-white d-block px-3 py-2 d-sm-flex justify-content-center align-items-center" %>
        <%= submit_tag "Save", class: "btn btn-outline-primary btn-border-radius text-white order-0 order-sm-2 d-block px-3 py-2 mb-2 mb-sm-0 ml-sm-3 justify-content-center align-items-center" %>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "components/ingredients/edit" %>
<%= render partial: "components/steps/edit" %>

<script>
  $(document).ready(function() {
    new Vue({
      el: $('.vueable')[0],
      data: { 
        recipeVersion: gon.recipe_version
      }
    });
  });
</script>

<script type="text/javascript">
  var autoExpand = function (field) {

  // Reset field height
  field.style.height = 'inherit';

  // Get the computed styles for the element
  var computed = window.getComputedStyle(field);

  // Calculate the height
  var height = parseInt(computed.getPropertyValue('border-top-width'), 10)
               + parseInt(computed.getPropertyValue('padding-top'), 10)
               + field.scrollHeight
               + parseInt(computed.getPropertyValue('padding-bottom'), 10)
               + parseInt(computed.getPropertyValue('border-bottom-width'), 10);
  field.style.height = height + 'px';
};
</script>

<script type="text/javascript">
  document.addEventListener('input', function (event) {
    if (event.target.tagName.toLowerCase() !== 'textarea') return;
    autoExpand(event.target);
  }, false);
</script>

app/views/recipe_versions/show.html.erb
<div class="mt-4">
  <div class="row">
    <div class="col text-right mt-1 d-none d-md-block">
      <div class="fa-stack fa-1x">
        <% if @recipe_version.locked_at.present? %>
          <%= icon('far', 'circle', class: 'text-danger fa-stack-2x') %>
          <%= icon('fas', 'lock', class: 'text-danger fa-stack-1x') %>
        <% else %>
          <%= icon('far', 'circle', class: 'text-primary fa-stack-2x') %>
          <%= icon('fas', 'unlock', class: 'text-primary fa-stack-1x') %>
        <% end %>
      </div>
    </div>

    <div class="col-10 mx-auto">

      <div class="text-left mt-1 d-block d-sm-block d-md-none">
        <div class="fa-stack fa-1x">
          <% if @recipe_version.locked_at.present? %>
            <%= icon('far', 'circle', class: 'text-danger fa-stack-2x') %>
            <%= icon('fas', 'lock', class: 'text-danger fa-stack-1x') %>
          <% else %>
            <%= icon('far', 'circle', class: 'text-primary fa-stack-2x') %>
            <%= icon('fas', 'unlock', class: 'text-primary fa-stack-1x') %>
          <% end %>
        </div>
      </div>

      <h1 class="font-weight-bolder"><%= @recipe_version.recipe.title %></h1>
      <div class="border-top w-25 pb-2">
      </div>
      <% if @recipe_version.description.present? %>
        <h5 class="font-weight-light"><%= @recipe_version.description %></h5>
      <% else %>
        <h5 class="font-weight-light">No description</h5>
      <% end %>
      <h6 class="text-muted font-weight-light">Created on <%= @recipe_version.created_at.strftime("%b %-d, %Y") %>
        <% if @recipe_version.locked_at.present? %>
        | Locked on <%= @recipe_version.locked_at.strftime("%b %-d, %Y") %>
        <% end %>
      </h6>

      <div class="row mt-4 mb-2">
        <div class="col-md-4 col-xs-10 mb-2">
          <div class="text-dark card h-100 bg-white border-0">
            <div class="card-body px-3 py-2">
              <h6 class="card-title mb-1">Ingredients</h6>
              <div class="col-5 border-top border-info pb-2"></div>
              <% @recipe_version.recipe_ingredients.each do |recipe_ingredient| %>
                <p class="mb-1 font-weight-light"> 
                  <%= number_with_precision(recipe_ingredient.amount, precision: 2, strip_insignificant_zeros: true) %> 
                  <%= recipe_ingredient.ingredient_measurement.name.pluralize(recipe_ingredient.amount) %>
                  <span class="font-weight-bold"><%= recipe_ingredient.ingredient.name %> </span>
                </p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-8 col-xs-10 mb-2">
          <div class="text-dark card h-100 bg-white border-0">
            <div class="card-body px-3 py-2">
              <h6 class="card-title mb-1">Steps</h6>
              <div class="col-1 border-top border-info pb-2">
              </div>
              <ol class="pl-3">
                <% @recipe_version.recipe_steps.each do |recipe_step| %>
                  <li class="mb-3 font-weight-light"> <%= recipe_step.step.content %> </li>
                <% end %>
              </ol>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12 col-sm-4 order-2 order-sm-0 d-sm-flex justify-content-start">

          <!--All Versions Button-->
          <%= link_to recipe_path(@recipe_version.recipe.hashid), :class=>"btn btn-outline-info btn-border-radius text-white d-none d-sm-block px-3 py-2 d-sm-flex justify-content-center align-items-center" do %> 
            <%= icon('fas', 'angle-left', class: 'text-white mr-1') %> All Versions
          <% end %>

          <%= link_to recipe_path(@recipe_version.recipe.hashid), :class=>"btn btn-outline-info btn-border-radius text-white d-block d-sm-none px-2 py-2 mb-2 justify-content-center align-items-center" do %> 
            <%= icon('fas', 'angle-left', class: 'text-white mr-1') %> All Versions
          <% end %>
        </div>

        <div class="col-12 col-sm-8 order-1 mb-2 mb-sm-0 d-inline-flex justify-content-center justify-content-sm-end">

          <!--Previous Version Button-->
          <% if @recipe_version.parent_recipe_version_id > 0 %>
            <%= link_to recipes_v_path(RecipeVersion.find_by(id: @recipe_version.parent_recipe_version_id)), :class=>"btn btn-outline-info btn-border-radius text-white mt-0 mr-2 px-2 px-sm-3 py-2 d-flex justify-content-center align-items-center" do %>
              <%= icon('fas', 'angle-left', class: 'text-white mr-1') %> Previous Version
            <% end %>
          <% end %>

          <!--Next Version Button-->
          <% if @recipe_version.locked_at.present? && @recipe_version.child_recipe_version.present? %>
            <%= link_to recipes_v_path(@recipe_version.child_recipe_version.hashid), :class=>"btn btn-outline-info btn-border-radius text-white mt-0 px-2 px-sm-3 py-2 d-flex justify-content-center align-items-center" do %>
              Next Version <%= icon('fas', 'angle-right', class: 'text-white ml-1') %>
            <% end %>

          <!--Create New Version Button-->
          <% elsif @recipe_version.locked_at.present? %>
            <%= link_to "Create New Version",
                new_recipes_v_version_path(v_id: @recipe_version.hashid),
                :class=>"btn btn-outline-primary btn-border-radius text-white d-block px-2 px-sm-3 py-2 justify-content-center align-items-center" %> 

          <!--Edit & Lock Version Buttons-->
          <% else %>
            <!--Edit Version Button-->
            <%= link_to edit_recipes_v_path(@recipe_version.hashid), :class=>"btn btn-outline-primary btn-border-radius text-white d-block px-2 px-sm-3 py-2 mr-2 d-flex justify-content-center align-items-center" do %>
              Edit This Version
            <% end %>
            
            <!--Lock Version Button-->
            <button class="btn btn-outline-danger btn-border-radius text-white d-none d-block px-2 px-sm-3 py-2 d-flex justify-content-center align-items-center" id="create_version">Lock This Version</button>

            <%= form_for(
              @recipe_version,
              url: recipes_v_path(id: @recipe_version.hashid),
              method: :put,
              html: {
                id: "confirm_version",
                class: "d-none"
              }
            ) do |f| %>
              <%= f.hidden_field :locked, value: true %>
              <%= f.submit "Click to Confirm",
                  :class=>"btn btn-outline-danger btn-border-radius text-white d-block px-2 px-sm-3 py-2 justify-content-center align-items-center" %>
            <% end %>
          <% end %>

        </div>

      </div>

    </div>
    <div class="col d-none d-md-block">
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $("#create_version").click(function() {
      $(this).removeClass('d-block');
      $(this).removeClass('d-flex');
      $("#confirm_version").removeClass('d-none');
      $("#confirm_version").addClass('d-flex');
      setTimeout(relockRecipe, 4000)
    });
  });

  function relockRecipe() {
    $("#create_version").addClass('d-block');
    $("#create_version").addClass('d-flex');
    $("#confirm_version").addClass('d-none');
    $("#confirm_version").removeClass('d-flex');
  }
</script>